### ISSUE TITLE
option "--directory" not working as expected

### ISSUE THREAD

**Issue by Avareto** [nxtend-team/nxtend#375]
Using "ng generate @nrwl/angular:application --name=applicationanme" with "--directory=directoryname" option generates the application under workspacename/apps/directoryname/applicationname. 
Using "nx generate @nxtend/ionic-angular:application" with --directory=directoryname" returns the following error message:

`
nx generate @nxtend/ionic-angular:application --dry-run --directory=directoryname --name=applicationname
Error: Cannot find project 'applicationname'
    at Object.getProjectConfig (C:\avareto\projects\ionic-mono\comapps\node_modules\@nrwl\workspace\src\utils\ast-utils.js:496:15)
    at Object.normalizeOptions (C:\avareto\projects\ionic-mono\comapps\node_modules\@nxtend\capacitor\src\schematics\capacitor-project\lib\normalize-options.js:8:47)
    at C:\avareto\projects\ionic-mono\comapps\node_modules\@nxtend\capacitor\src\schematics\capacitor-project\schematic.js:12:55
    at MergeMapSubscriber.pipe.operators_1.mergeMap.inputTree [as project] (C:\avareto\projects\ionic-mono\comapps\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (C:\avareto\projects\ionic-mono\comapps\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
    at MergeMapSubscriber._next (C:\avareto\projects\ionic-mono\comapps\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (C:\avareto\projects\ionic-mono\comapps\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (C:\avareto\projects\ionic-mono\comapps\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (C:\avareto\projects\ionic-mono\comapps\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:44:25)  
    at Observable.subscribe (C:\avareto\projects\ionic-mono\comapps\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:30:22)      
Cannot find project 'applicationname'
`

**Comment by devinshoemaker** [comment]
Thank you for the issue! I have identified the issue and am working on a fix.

**Comment by devinshoemaker** [comment]
This issue has been fixed and release with Nxtend 11.
