### ISSUE TITLE
macOS Big Sur ios critical workflow path issues

### ISSUE THREAD

**Issue by troywweber7** [nxtend-team/nxtend#403]
I'm hoping to shed some light on the following error:

```bash
% yarn nx run old-ekg:copy:ios 
yarn run v1.22.10
$ nx run old-ekg:copy:ios

> nx run old-ekg:copy:ios 
command not found: cap
(node:17882) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at Object.error (/Users/troyw/Code/old-ekg-workspace/node_modules/@nrwl/tao/src/shared/logger.js:10:15)
    at Object.<anonymous> (/Users/troyw/Code/old-ekg-workspace/node_modules/@nrwl/tao/src/shared/params.js:17:33)
    at Generator.throw (<anonymous>)
    at rejected (/Users/troyw/Code/old-ekg-workspace/node_modules/tslib/tslib.js:115:69)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 7.01s.
```

I'm relatively new to macOS so any help handling this issue or being pointed in the right direction would be greatly appreciated.

*UPDATE*

The above error magically went away, but I'm still having issues with the critical workflow path for ios. For comparison, the workflow path for android is successful on Big Sur (short of opening android studio):

```bash
% yarn nx copy:android old-ekg && yarn nx sync:android old-ekg 
yarn run v1.22.10
$ nx copy:android old-ekg
✔ Copying web assets from old-ekg to android/app/src/main/assets/public in 1.19s
✔ Copying native bridge in 3.44ms
✔ Copying capacitor.config.json in 2.80ms
✔ copy in 1.22s
✨  Done in 3.43s.
yarn run v1.22.10
$ nx sync:android old-ekg
warning package.json: No license field
warning old-ekg: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✔ Copying web assets from old-ekg to android/app/src/main/assets/public in 2.22s
✔ Copying native bridge in 8.42ms
✔ Copying capacitor.config.json in 12.15ms
✔ copy in 2.26s
✔ Updating Android plugins in 14.83ms
  Found 0 Capacitor plugins for android:
✔ update android in 70.50ms
Sync finished in 2.35s
✨  Done in 5.00s.
```

After this, you would open in android studio using `yarn nx open:android old-ekg`. Now compare to the same workflow path with ios:

```bash
% yarn nx copy:ios old-ekg && yarn nx sync:ios old-ekg    
yarn run v1.22.10
$ nx copy:ios old-ekg
✔ Copying web assets from old-ekg to ios/App/public in 962.63ms
✔ Copying native bridge in 3.70ms
✔ Copying capacitor.config.json in 4.25ms
✔ copy in 992.99ms
✨  Done in 3.13s.
yarn run v1.22.10
$ nx sync:ios old-ekg
warning package.json: No license field
warning old-ekg: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
[error] cocoapods is not installed. For information: https://guides.cocoapods.org/using/getting-started.html#installation
(node:21160) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at Object.error (/Users/troyw/Code/old-ekg-workspace/node_modules/@nrwl/tao/src/shared/logger.js:10:15)
    at Object.<anonymous> (/Users/troyw/Code/old-ekg-workspace/node_modules/@nrwl/tao/src/shared/params.js:17:33)
    at Generator.throw (<anonymous>)
    at rejected (/Users/troyw/Code/old-ekg-workspace/node_modules/tslib/tslib.js:115:69)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 2.21s.
```

If this command were succeeding, you would then open with xcode with `yarn nx open:ios old-ekg`. Unfortunately, I get the error above so I can't proceed to verify the entire workflow path for ios just yet.

Of course I'm not going to stop looking. Hopefully it's as simple as installing `cocoapods`. I just expected that to be installed locally, which may not be the case...

**Comment by troywweber7** [comment]
Closing as I didn't read capacitor documentation well enough: https://capacitorjs.com/docs/getting-started/dependencies#ios-development
