### ISSUE TITLE
calling the plugin from a generator causes error

### ISSUE THREAD

**Issue by tassie-chris** [nxtend-team/nxtend#579]
using the plugin from a generator causes an error with the latest migrations - 13.3.6

```node
const appGenerator = wrapAngularDevkitSchematic(
    '@nxtend/ionic-angular',
    'app'
  );
 await appGenerator(tree, {
      name: myApp
    }),
```

NOT SUPPORTED: keyword "id", use "$id" for schema ID

```node
 at Object.code (...ajv/dist/vocabularies/core/id.js:6:15)
at keywordCode (.../ajv/dist/compile/validate/index.js:454:13)
```

12.10.1 works fine.

**Comment by devinshoemaker** [comment]
This may get resolved when I release the official v13 update that's built on Nx 13. This is in progress now, but with the holidays I don't have a solid ETA.

**Comment by devinshoemaker** [comment]
Nxtend 13.0.0 has been released. Can you update and let me know if you have issues?

**Comment by cherry-tom** [comment]
It works if i change @nxtend/ionic-angular/src/generators/application/schema.json line 4: 

"id": "IonicAngularApp",
to...
"$id": "IonicAngularApp"
