### ISSUE TITLE
Cannot find module 'nx/src/utils/app-root'

### ISSUE THREAD

**Issue by Jeff-Stapleton** [nxtend-team/nxtend#632]
I am trying to create an NX monorepo for an ionic react app I am building.

I create the nx workspace like so:
`npx create-nx-workspace my-org --preset=empty` 

Then I installed installed the required dependencies:
`npm install --save-dev --exact @nxtend/ionic-react @nxtend/capacitor @nrwl/react`

Finally I am trying to generate my ionic-react app using the following command:
`nx generate @nxtend/ionic-react:application myApp`

However I am getting the following error:
```
>  NX  Generating @nxtend/ionic-react:application

✔ Which starter template would you like to use? · tabs
Cannot find module 'nx/src/utils/app-root'
Require stack:
- /Users/jeffstapleton/Documents/Github/integrations-front-end/node_modules/@nxtend/ionic-react/node_modules/@nrwl/devkit/index.js
- /Users/jeffstapleton/Documents/Github/integrations-front-end/node_modules/@nxtend/ionic-react/src/generators/application/generator.js
- /Users/jeffstapleton/Documents/Github/integrations-front-end/node_modules/nx/src/config/workspaces.js
- /Users/jeffstapleton/Documents/Github/integrations-front-end/node_modules/nx/src/command-line/generate.js
- /Users/jeffstapleton/Documents/Github/integrations-front-end/node_modules/nx/src/command-line/nx-commands.js
- /Users/jeffstapleton/Documents/Github/integrations-front-end/node_modules/nx/bin/init-local.js
- /Users/jeffstapleton/Documents/Github/integrations-front-end/node_modules/nx/bin/nx.js
- /Users/jeffstapleton/Documents/Github/integrations-front-end/node_modules/@nrwl/cli/bin/nx.js
- /Users/jeffstapleton/.nvm/versions/node/v14.15.0/lib/node_modules/nx/node_modules/@nrwl/cli/bin/nx.js
- /Users/jeffstapleton/.nvm/versions/node/v14.15.0/lib/node_modules/nx/bin/nx.js
```

For the sake of being thurough I will include my entire `package.json` here in case the problem is with my specific version:
```
{
  "name": "integrations-front-end",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@capacitor/core": "3.5.1",
    "@ionic/react-router": "6.1.9",
    "@testing-library/jest-dom": "5.16.4",
    "@testing-library/react": "13.3.0",
    "@testing-library/user-event": "14.2.0",
    "@types/jest": "28.1.1",
    "@types/node": "17.0.41",
    "@types/react": "18.0.12",
    "@types/react-dom": "18.0.5",
    "@types/react-router": "5.1.18",
    "@types/react-router-dom": "5.3.3",
    "ionicons": "6.0.2",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-router": "6.3.0",
    "react-router-dom": "6.3.0",
    "react-scripts": "5.0.1",
    "typescript": "4.7.3",
    "web-vitals": "2.1.4",
    "workbox-background-sync": "6.5.3",
    "workbox-broadcast-update": "6.5.3",
    "workbox-cacheable-response": "6.5.3",
    "workbox-core": "6.5.3",
    "workbox-expiration": "6.5.3",
    "workbox-google-analytics": "6.5.3",
    "workbox-navigation-preload": "6.5.3",
    "workbox-precaching": "6.5.3",
    "workbox-range-requests": "6.5.3",
    "workbox-routing": "6.5.3",
    "workbox-strategies": "6.5.3",
    "workbox-streams": "6.5.3",
    "@ionic-native/core": "5.36.0",
    "@ionic-native/splash-screen": "5.36.0",
    "@ionic-native/status-bar": "5.36.0",
    "@ionic/react": "6.1.9",
    "@nrwl/workspace": "14.2.4"
  },
  "devDependencies": {
    "@capacitor/android": "3.5.1",
    "@capacitor/cli": "3.5.1",
    "@capacitor/ios": "3.5.1",
    "@nrwl/cli": "14.2.4",
    "@nrwl/cypress": "14.2.4",
    "@nrwl/eslint-plugin-nx": "14.2.4",
    "@nrwl/jest": "14.2.4",
    "@nrwl/linter": "14.2.4",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/react": "^14.2.4",
    "@nrwl/tao": "14.2.4",
    "@nrwl/workspace": "14.2.4",
    "@nxtend/capacitor": "^13.0.0",
    "@nxtend/ionic-react": "^13.0.0",
    "nx": "14.2.4",
    "prettier": "2.6.2",
    "typescript": "4.7.2"
  }
}

```

**Comment by 0x1ad2** [comment]
Hi @Jeff-Stapleton! I'm encountering the exact same problem.

I tried to apply the solutions mentioned here, but no luck so far https://github.com/nrwl/nx/issues/4731

Could you paste your report here, using `npx nx report` you can generate it, here is mine:

```
 Node : 16.15.0
   OS   : darwin x64
   npm  : 8.5.5
   
   nx : 14.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : 14.2.4
   @nrwl/linter : 14.2.4
   @nrwl/nest : Not Found
   @nrwl/next : 14.2.4
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.2.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : 14.2.4
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @nxtend/capacitor: 13.0.0
```

**Comment by 0x1ad2** [comment]
Alright so you porbably have to options

* Roll back to  `@nxtend/capacitor` version `12.1.0`
* `cd` inside your container directory and run `npx cap --help` to find what you could do without downgrading   `@nxtend/capacitor`

**Comment by rjlopezdev** [comment]
Same issue here with `cap sync` command.
This happens since I upgrade to Nx `v^14.x.x`

**Comment by Stevoohh** [comment]
Same issue. Any progress on this ?

Cannot find module 'nx/src/utils/app-root'

**Comment by mtiahrt** [comment]
same problem with Angular also. Tried version 12 and it also didn't work for me.

**Comment by Tam2** [comment]
Downgrading back to 14.1.7 works

**Comment by dandouglas** [comment]
Same issue here

```
Node : 14.17.0
   OS   : darwin arm64
   npm  : 6.14.13
   
   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.1.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
         @nxtend/capacitor: 13.0.0
```

**Comment by llnathanll** [comment]
@dandouglas, @Tam2 - did you downgrade nx and all plugins to 14.1.7?  And did you use the nx version migration, or did you just change the versions by hand?  Asking because this fix did not work for me.

**Comment by llnathanll** [comment]
nk_mac@Nathans-iMac super-cap % npx nx generate @nxtend/capacitor:capacitor-project --project mobile --verbose
✔ What app ID would you like to use? · com.embue.mobile
✔ What app name would you like to use? · super
The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:388:5)
    at validateString (node:internal/validators:114:11)
    at normalize (node:path:1128:5)
    at offsetFromRoot (/Users/nk_mac/Projects/MonoRepo/super-cap/node_modules/@nxtend/capacitor/node_modules/@nrwl/devkit/src/utils/offset-from-root.js:18:40)
    at addCapacitorConfig (/Users/nk_mac/Projects/MonoRepo/super-cap/node_modules/@nxtend/capacitor/src/generators/capacitor-project/lib/add-capacitor-config.js:6:170)
    at /Users/nk_mac/Projects/MonoRepo/super-cap/node_modules/@nxtend/capacitor/src/generators/capacitor-project/generator.js:16:55
    at Generator.next (<anonymous>)
    at /Users/nk_mac/Projects/MonoRepo/super-cap/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/nk_mac/Projects/MonoRepo/super-cap/node_modules/tslib/tslib.js:114:16)
nk_mac@Nathans-iMac super-cap % npx nx report

**Comment by llnathanll** [comment]
This is the output I get from a clean install using `npx create-nx-workspace@14.1.7` and `npm install --save-dev @nxtend/cpacitor` and then running the following generator.  Nx report at the end.  From the stacktrace it looks like a value for path was returned as undefined, but I don't see what is causing this.  Any help appreciated.
```
% npx nx generate @nxtend/capacitor:capacitor-project --project mobile --verbose
✔ What app ID would you like to use? · com.hostname.mobile
✔ What app name would you like to use? · mobile-app
The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:388:5)
    at validateString (node:internal/validators:114:11)
    at normalize (node:path:1128:5)
    at offsetFromRoot (/Users/nk/Projects/MonoRepo/super-cap/node_modules/@nxtend/capacitor/node_modules/@nrwl/devkit/src/utils/offset-from-root.js:18:40)
    at addCapacitorConfig (/Users/nk/Projects/MonoRepo/super-cap/node_modules/@nxtend/capacitor/src/generators/capacitor-project/lib/add-capacitor-config.js:6:170)
    at /Users/nk/Projects/MonoRepo/super-cap/node_modules/@nxtend/capacitor/src/generators/capacitor-project/generator.js:16:55
    at Generator.next (<anonymous>)
    at /Users/nk/Projects/MonoRepo/super-cap/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/nk/Projects/MonoRepo/super-cap/node_modules/tslib/tslib.js:114:16)
% npx nx report
>  NX   Report complete - copy this into the issue template

   Node : 18.4.0
   OS   : darwin x64
   npm  : 6.14.12

   nx : 14.1.7
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.7
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.7
   @nrwl/web : 14.1.7
   @nrwl/workspace : 14.1.7
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
   	 @nxtend/capacitor: 13.0.0
```

**Comment by SimonPrammer** [comment]
Any updates on this? Unable to create a ionic workspace with nxtend aswell

**Comment by SimonPrammer** [comment]
For me downgrading NX did not solve the issue. Neither 13.0.0 nor 14.1.7 seemed to do the trick.

**Comment by mackelito** [comment]
> Thanks @Tam2 downgrading to 14.1.7 did indeed work. Hopefully this issue will be fixed soon 🤞

What steps did you take to downgrade?
Looking at doing the same and don't want to miss anything :)

**Comment by Tam2** [comment]
I manually changed the versions in package.json to 14.1.7, deleted the node_modules folder and then ran `npm install`

**Comment by muuvmuuv** [comment]
For anyone that wants a patch:

<details>
<summary>Details</summary>

```diff
diff --git a/src/executors/run-commands/run-commands.impl.js b/src/executors/run-commands/run-commands.impl.js
index d2c45a4405755b63e541b060f0e7631781f33b9c..052e0a4c172454d8c3cfae567739baa5fc1e3be6 100644
--- a/src/executors/run-commands/run-commands.impl.js
+++ b/src/executors/run-commands/run-commands.impl.js
@@ -190,7 +190,7 @@ function interpolateArgsIntoCommand(command, opts, forwardAllArgs) {
         return command.replace(regex, (_, group) => opts.parsedArgs[group]);
     }
     else if (forwardAllArgs) {
-        return `${command}${opts.__unparsed__.length > 0 ? ' ' + opts.__unparsed__.join(' ') : ''}`;
+        return `${command}${opts.__unparsed__?.length > 0 ? ' ' + opts.__unparsed__.join(' ') : ''}`;
     }
     else {
         return command;
diff --git a/src/utils/app-root.d.ts b/src/utils/app-root.d.ts
new file mode 100644
index 0000000000000000000000000000000000000000..9d8d8966d6d98539c395ce6d7c95333f7ab35474
--- /dev/null
+++ b/src/utils/app-root.d.ts
@@ -0,0 +1,11 @@
+/**
+ * The root of the workspace.
+ *
+ * @deprecated use workspaceRoot instead
+ */
+export declare const appRootPath: string;
+/**
+ * The root of the workspace
+ */
+export declare const workspaceRoot: string;
+export declare function fileExists(filePath: string): boolean;
diff --git a/src/utils/app-root.js b/src/utils/app-root.js
new file mode 100644
index 0000000000000000000000000000000000000000..440e99787ed3facbe77e036f17d7f49ff90789cb
--- /dev/null
+++ b/src/utils/app-root.js
@@ -0,0 +1,39 @@
+"use strict";
+Object.defineProperty(exports, "__esModule", { value: true });
+exports.fileExists = exports.workspaceRoot = exports.appRootPath = void 0;
+const path = require("path");
+const fs_1 = require("fs");
+/**
+ * The root of the workspace.
+ *
+ * @deprecated use workspaceRoot instead
+ */
+exports.appRootPath = pathInner(__dirname);
+/**
+ * The root of the workspace
+ */
+exports.workspaceRoot = exports.appRootPath;
+function pathInner(dir) {
+    if (process.env.NX_WORKSPACE_ROOT_PATH)
+        return process.env.NX_WORKSPACE_ROOT_PATH;
+    if (path.dirname(dir) === dir)
+        return process.cwd();
+    if (fileExists(path.join(dir, 'workspace.json')) ||
+        fileExists(path.join(dir, 'nx.json')) ||
+        fileExists(path.join(dir, 'angular.json'))) {
+        return dir;
+    }
+    else {
+        return pathInner(path.dirname(dir));
+    }
+}
+function fileExists(filePath) {
+    try {
+        return (0, fs_1.statSync)(filePath).isFile();
+    }
+    catch (err) {
+        return false;
+    }
+}
+exports.fileExists = fileExists;
+//# sourceMappingURL=app-root.js.map
\ No newline at end of file
diff --git a/src/utils/app-root.js.map b/src/utils/app-root.js.map
new file mode 100644
index 0000000000000000000000000000000000000000..d8068dc95b667de1d6c5f5af8d2fd616ed328f97
--- /dev/null
+++ b/src/utils/app-root.js.map
@@ -0,0 +1 @@
+{"version":3,"file":"app-root.js","sourceRoot":"","sources":["../../../../../packages/nx/src/utils/app-root.ts"],"names":[],"mappings":";;;AAAA,6BAA6B;AAC7B,2BAA8B;AAE9B;;;;GAIG;AACU,QAAA,WAAW,GAAG,SAAS,CAAC,SAAS,CAAC,CAAC;AAEhD;;GAEG;AACU,QAAA,aAAa,GAAG,mBAAW,CAAC;AAEzC,SAAS,SAAS,CAAC,GAAW;IAC5B,IAAI,OAAO,CAAC,GAAG,CAAC,sBAAsB;QACpC,OAAO,OAAO,CAAC,GAAG,CAAC,sBAAsB,CAAC;IAC5C,IAAI,IAAI,CAAC,OAAO,CAAC,GAAG,CAAC,KAAK,GAAG;QAAE,OAAO,OAAO,CAAC,GAAG,EAAE,CAAC;IACpD,IACE,UAAU,CAAC,IAAI,CAAC,IAAI,CAAC,GAAG,EAAE,gBAAgB,CAAC,CAAC;QAC5C,UAAU,CAAC,IAAI,CAAC,IAAI,CAAC,GAAG,EAAE,SAAS,CAAC,CAAC;QACrC,UAAU,CAAC,IAAI,CAAC,IAAI,CAAC,GAAG,EAAE,cAAc,CAAC,CAAC,EAC1C;QACA,OAAO,GAAG,CAAC;KACZ;SAAM;QACL,OAAO,SAAS,CAAC,IAAI,CAAC,OAAO,CAAC,GAAG,CAAC,CAAC,CAAC;KACrC;AACH,CAAC;AAED,SAAgB,UAAU,CAAC,QAAgB;IACzC,IAAI;QACF,OAAO,IAAA,aAAQ,EAAC,QAAQ,CAAC,CAAC,MAAM,EAAE,CAAC;KACpC;IAAC,OAAO,GAAG,EAAE;QACZ,OAAO,KAAK,CAAC;KACd;AACH,CAAC;AAND,gCAMC"}
\ No newline at end of file
```

</details>

**Comment by orl99** [comment]
> 

How and where can I apply this patch?

**Comment by mackelito** [comment]
> For anyone that want a patch, here. This also includes #633.
> 
> Details
> How?
> 
> * pnpm
>   
>   * copy contents into a file `patches/nx@14.4.3.patch`
>   * add to package.json `"pnpm": { "patchedDependencies": { "nx@14.4.3": "patches/nx@14.4.3.patch" } }`
>   * `pnpm install`
> * yarn
>   
>   * similar to pnpm: [yarnpkg.com/cli/patch-commit#details](https://yarnpkg.com/cli/patch-commit#details)
> * npm
>   
>   * no support

Would https://www.npmjs.com/package/patch-package work?

**Comment by yannickcare** [comment]
Downgrade to nrwl/*@14.1.7 still having the same issue.

**Comment by yannickcare** [comment]
> > For anyone that want a patch, here. This also includes #633.
> > Details
> > How?
> > 
> > * pnpm
> >   
> >   * copy contents into a file `patches/nx@14.4.3.patch`
> >   * add to package.json `"pnpm": { "patchedDependencies": { "nx@14.4.3": "patches/nx@14.4.3.patch" } }`
> >   * `pnpm install`
> > * yarn
> >   
> >   * similar to pnpm: [yarnpkg.com/cli/patch-commit#details](https://yarnpkg.com/cli/patch-commit#details)
> > * npm
> >   
> >   * no support
> 
> Would https://www.npmjs.com/package/patch-package work?

Is this patch to be applied to the latest version or 14.1.7?

**Comment by yannickcare** [comment]
> * nx@14.4.3

Is there a way to do this with https://www.npmjs.com/package/patch-package

**Comment by ntgussoni** [comment]
> 



> For anyone that want a patch, here. This also includes #633.
> 
> Details
> How?
> 
> * pnpm
>   
>   * copy contents into a file `patches/nx@14.4.3.patch`
>   * add to package.json `"pnpm": { "patchedDependencies": { "nx@14.4.3": "patches/nx@14.4.3.patch" } }`
>   * `pnpm install`
> * yarn
>   
>   * similar to pnpm: https://yarnpkg.com/cli/patch-commit#details
> * npm
>   
>   * no support

Thanks a lot! This worked for us

**Comment by SimonPrammer** [comment]
Still waiting for an "official" fix.
Would be great to at least get some message if it will be looked into.

**Comment by devinshoemaker** [comment]
These plugins are moving over to the Nxext repo, and an Nx 14 version has been released. There are some migration guides on their docs site, here's a link to the Ionic Angular guide: https://nxext.dev/docs/ionic-angular/migrating-from-nxtend.html
